# Generated by Django 6.0.6 on 2026-09-26 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carbon_result_ids', models.JSONField(help_text='List of inference-side CarbonResult.id values substantiating this submission')),
                ('provenance_chain_hash_at_submission', models.CharField(help_text="Snapshot of provenance.py's latest hash at submission time - proves state of evidence", max_length=64)),
                ('payload_sent', models.JSONField(help_text='Complete JSON payload transmitted to national registry national-api')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status returned by registry endpoint', null=True)),
                ('response_body', models.JSONField(blank=True, help_text='Raw or parsed response payload returned by national registry', null=True)),
                ('submission_status', models.CharField(choices=[('pending', 'pending'), ('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('failed', 'failed')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitoring Report Submission',
                'verbose_name_plural': 'Monitoring Report Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PositiveNegativeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(help_text="Registry sector (or '*' for all)", max_length=100)),
                ('mitigation_type', models.CharField(default='*', help_text="Specific activity or '*' for all", max_length=100)),
                ('ndc_commitment_type', models.CharField(choices=[('unconditional', 'unconditional'), ('conditional', 'conditional'), ('beyond_ndc', 'beyond_ndc'), ('any', 'any')], default='any', help_text='NDC category requirement', max_length=50)),
                ('status', models.CharField(choices=[('positive_list', 'positive_list'), ('negative_list', 'negative_list'), ('pending_review', 'pending_review')], default='pending_review', max_length=20)),
                ('regulatory_reference', models.CharField(blank=True, help_text='DOE Gazette notification, NDC 3.0 Annex, or Article 6 DNA circular', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Positive/Negative List Rule',
                'verbose_name_plural': 'Positive/Negative List Rules',
                'ordering': ['sector', 'mitigation_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistryProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_project_id', models.CharField(blank=True, help_text='Assigned by DOE/Registry (e.g. CA0004-VU-CH-356, BD-JCM-004)', max_length=64, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('sector', models.CharField(help_text='Registry sector enum (e.g. Forestry, Agriculture, Energy)', max_length=100)),
                ('sectoral_scope', models.CharField(help_text='UNFCCC / CDM Sectoral Scope identifier', max_length=100)),
                ('mitigation_type', models.CharField(help_text='e.g. Afforestation, Methane Avoidance, Solar Irrigation', max_length=100)),
                ('company_tax_id', models.CharField(help_text='Registry requires this organization Tax ID / BIN', max_length=64)),
                ('ndc_commitment_type', models.CharField(choices=[('unconditional', 'unconditional'), ('conditional', 'conditional'), ('beyond_ndc', 'beyond_ndc')], default='conditional', help_text='Categorization under Bangladesh NDC 3.0', max_length=50)),
                ('eligibility_status', models.CharField(choices=[('pending_review', 'pending_review'), ('positive_list', 'positive_list'), ('negative_list', 'negative_list')], default='pending_review', help_text='Assessed against DOE Positive/Negative List before registry onboarding', max_length=20)),
                ('carbon_standard', models.CharField(help_text='Standard under which credits are verified: Verra / Gold Standard / PACM / JCM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registry Project',
                'verbose_name_plural': 'Registry Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondingAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_serial_number', models.CharField(blank=True, help_text='Filled in once national registry issues the batch serial range', max_length=100, null=True)),
                ('authorized_for_itmo', models.BooleanField(default=False, help_text='Flagged by Bangladesh Article 6 Designated National Authority (DNA) for international transfer')),
                ('itmo_transfer_partner', models.CharField(blank=True, help_text='Acquiring Party / Partner country (e.g. Japan, Switzerland)', max_length=100, null=True)),
                ('adjustment_applied', models.BooleanField(default=False, help_text='Explicit confirmation that corresponding adjustment has been added to national GHG balance')),
                ('adjustment_applied_at', models.DateTimeField(blank=True, help_text='Timestamp when DOE officially confirmed adjustment application', null=True)),
                ('adjustment_confirmation_id', models.CharField(blank=True, help_text='Official DOE / UNFCCC Article 6.2 registry confirmation reference', max_length=100, null=True)),
                ('ndc_inventory_sector', models.CharField(choices=[('LULUCF_Forestry', 'LULUCF / Forestry'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Waste', 'Waste'), ('IPPU', 'Industrial Processes and Product Use')], default='LULUCF_Forestry', help_text='Which BTR national inventory sector this mitigation outcome reduces', max_length=100)),
                ('metric_tonnes_co2e', models.FloatField(default=0.0, help_text='Total verified tCO2e to be adjusted in Bangladesh national accounts')),
                ('vintage_year', models.IntegerField(blank=True, help_text='Vintage year of emission reduction', null=True)),
                ('reconciliation_status', models.CharField(choices=[('pending_issuance', 'pending_issuance'), ('issued_unadjusted', 'issued_unadjusted'), ('adjusted_confirmed', 'adjusted_confirmed'), ('contested', 'contested')], default='pending_issuance', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoring_report_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corresponding_adjustments', to='national_registry_bridge.monitoringreportsubmission')),
            ],
            options={
                'verbose_name': 'Corresponding Adjustment',
                'verbose_name_plural': 'Corresponding Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monitoringreportsubmission',
            name='registry_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='national_registry_bridge.registryproject'),
        ),
    ]
