# Generated by Django 6.0.6 on 2026-06-22 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=50)),
                ('needs_agronomist_review', models.BooleanField(default=False)),
                ('field_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
