# Generated by Django 6.0.6 on 2026-06-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('disease_risk_type', models.CharField(max_length=100)),
                ('risk_index', models.FloatField(help_text='0.0 to 1.0')),
                ('summary_bn', models.TextField(help_text='Bangla summary of the weather risk')),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='carbon_asset_risk',
            field=models.BooleanField(default=False, help_text='True if a Tier B tree has moderate/severe disease'),
        ),
    ]
