# Generated by Django 6.0.6 on 2026-06-22 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0002_weatherrisksnapshot_diagnosis_carbon_asset_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='model_version',
            field=models.CharField(default='v1.0.0-int8', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='treatment_shown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers_ai.weatherrisksnapshot'),
        ),
    ]
