# Generated by Django 6.0.6 on 2026-06-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0003_diagnosis_model_version_diagnosis_treatment_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='region',
            field=models.CharField(default='unknown', help_text='Upazila/Region for MRV aggregation', max_length=100),
        ),
    ]
