# Generated by Django 6.0.6 on 2026-06-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0004_diagnosis_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgronomistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agronomist_id', models.CharField(max_length=100)),
                ('verified_disease', models.CharField(max_length=100)),
                ('confidence_override', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agronomist_review', to='farmers_ai.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(help_text='Mock S3 object key', max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farmers_ai.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('organic', 'Organic'), ('chemical', 'Chemical')], max_length=50)),
                ('instructions_bn', models.TextField()),
                ('dosage_info', models.TextField(blank=True, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='farmers_ai.diagnosis')),
            ],
        ),
    ]
