# Generated by Django 6.0.6 on 2026-06-24 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0005_agronomistreview_cropimage_treatmentrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('air_quality', models.IntegerField()),
                ('co2', models.IntegerField()),
            ],
        ),
    ]
