# Generated by Django 6.0.6 on 2026-06-29 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_ai', '0006_carbontelemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('polygon_geojson', models.TextField()),
                ('analysis_type', models.CharField(default='ndvi', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('message', models.TextField()),
                ('suggested_action', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedBoundary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('boundary_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=50)),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='farmers_ai.analysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_biomass', models.FloatField()),
                ('estimated_carbon', models.FloatField()),
                ('tonnes_co2e', models.FloatField()),
                ('avg_ndvi', models.FloatField()),
                ('forest_area_ha', models.FloatField()),
                ('confidence', models.FloatField()),
                ('satellite_sources', models.CharField(default='Sentinel-2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='farmers_ai.analysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_type', models.CharField(max_length=50)),
                ('layer_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='farmers_ai.analysisjob')),
            ],
        ),
    ]
